In [1]:
%pip install tensorflow-gpu

     |████████████████████████████████| 421.8MB 38kB/s 
     |████████████████████████████████| 450kB 47.5MB/s 
     |████████████████████████████████| 3.9MB 47.1MB/s 
ERROR: tensorflow 1.15.0 has requirement tensorboard<1.16.0,>=1.15.0, but you'll have tensorboard 2.1.1 which is incompatible.
ERROR: tensorflow 1.15.0 has requirement tensorflow-estimator==1.15.1, but you'll have tensorflow-estimator 2.1.0 which is incompatible.
ERROR: tensorflow-federated 0.12.0 has requirement tensorflow~=2.1.0, but you'll have tensorflow 1.15.0 which is incompatible.
ERROR: tensorflow-federated 0.12.0 has requirement tensorflow-addons~=0.7.0, but you'll have tensorflow-addons 0.8.3 which is incompatible.
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0


In [0]:
import tensorflow as tf
import numpy as np
import os

In [17]:
file_data=tf.keras.utils.get_file('file','https://raw.githubusercontent.com/projjal1/datasets/master/human_chat.txt')

122880/115941 [===============================] - 0s 0us/step


In [0]:
text=open(file_data,'rb').read()

In [0]:
text=text.decode(encoding='utf-8')

In [24]:
print(text[:220])

Human 1: Hi!
Human 2: What is your favorite holiday?
Human 1: one where I get to meet lots of different people.
Human 2: What was the most number of people you have ever met during a holiday?
Human 1: Hard to keep a coun


In [0]:
#now building a vocab of words 
vocab=sorted(set(text))

In [26]:
#no. of chars in vocab
print(len(vocab))

101


In [27]:
#lets hash these characters 
mapping={v:u for u,v in enumerate(vocab)}
print(mapping)

{'\n': 0, ' ': 1, '!': 2, '"': 3, '%': 4, '&': 5, "'": 6, '(': 7, ')': 8, '*': 9, '+': 10, ',': 11, '-': 12, '.': 13, '/': 14, '0': 15, '1': 16, '2': 17, '3': 18, '4': 19, '5': 20, '6': 21, '7': 22, '9': 23, ':': 24, ';': 25, '<': 26, '>': 27, '?': 28, 'A': 29, 'B': 30, 'C': 31, 'D': 32, 'E': 33, 'F': 34, 'G': 35, 'H': 36, 'I': 37, 'J': 38, 'K': 39, 'L': 40, 'M': 41, 'N': 42, 'O': 43, 'P': 44, 'Q': 45, 'R': 46, 'S': 47, 'T': 48, 'U': 49, 'V': 50, 'W': 51, 'X': 52, 'Y': 53, 'Z': 54, '\\': 55, '_': 56, 'a': 57, 'b': 58, 'c': 59, 'd': 60, 'e': 61, 'f': 62, 'g': 63, 'h': 64, 'i': 65, 'j': 66, 'k': 67, 'l': 68, 'm': 69, 'n': 70, 'o': 71, 'p': 72, 'q': 73, 'r': 74, 's': 75, 't': 76, 'u': 77, 'v': 78, 'w': 79, 'x': 80, 'y': 81, 'z': 82, '~': 83, 'é': 84, '’': 85, '“': 86, '”': 87, '…': 88, '湘': 89, '留': 90, '）': 91, '：': 92, '😀': 93, '😂': 94, '😆': 95, '😉': 96, '😐': 97, '😛': 98, '😞': 99, '🙂': 100}


In [28]:
#character array
char_arr=np.array(vocab)
print(char_arr)

['\n' ' ' '!' '"' '%' '&' "'" '(' ')' '*' '+' ',' '-' '.' '/' '0' '1' '2'
 '3' '4' '5' '6' '7' '9' ':' ';' '<' '>' '?' 'A' 'B' 'C' 'D' 'E' 'F' 'G'
 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W' 'X' 'Y'
 'Z' '\\' '_' 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o'
 'p' 'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z' '~' 'é' '’' '“' '”' '…' '湘'
 '留' '）' '：' '😀' '😂' '😆' '😉' '😐' '😛' '😞' '🙂']


In [0]:
#now encoding our text 
text_as_int=np.array([mapping[each] for each in text])

In [0]:
#let's convert text to tensor slices

sequence_len=100
ex_per_epoch=len(text)//(sequence_len+1)

char_ds=tf.data.Dataset.from_tensor_slices(text_as_int)

In [0]:
sequences=char_ds.batch(sequence_len+1,drop_remainder=True)

In [0]:
#creating dataset by splitting them into chunks with both space for input and target
def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

dataset = sequences.map(split_input_target)

In [35]:
print(dataset)

<MapDataset shapes: ((100,), (100,)), types: (tf.int64, tf.int64)>


In [36]:
for each in dataset.take(2):
  print(each)

(<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([36, 77, 69, 57, 70,  1, 16, 24,  1, 36, 65,  2,  0, 36, 77, 69, 57,
       70,  1, 17, 24,  1, 51, 64, 57, 76,  1, 65, 75,  1, 81, 71, 77, 74,
        1, 62, 57, 78, 71, 74, 65, 76, 61,  1, 64, 71, 68, 65, 60, 57, 81,
       28,  0, 36, 77, 69, 57, 70,  1, 16, 24,  1, 71, 70, 61,  1, 79, 64,
       61, 74, 61,  1, 37,  1, 63, 61, 76,  1, 76, 71,  1, 69, 61, 61, 76,
        1, 68, 71, 76, 75,  1, 71, 62,  1, 60, 65, 62, 62, 61, 74])>, <tf.Tensor: shape=(100,), dtype=int64, numpy=
array([77, 69, 57, 70,  1, 16, 24,  1, 36, 65,  2,  0, 36, 77, 69, 57, 70,
        1, 17, 24,  1, 51, 64, 57, 76,  1, 65, 75,  1, 81, 71, 77, 74,  1,
       62, 57, 78, 71, 74, 65, 76, 61,  1, 64, 71, 68, 65, 60, 57, 81, 28,
        0, 36, 77, 69, 57, 70,  1, 16, 24,  1, 71, 70, 61,  1, 79, 64, 61,
       74, 61,  1, 37,  1, 63, 61, 76,  1, 76, 71,  1, 69, 61, 61, 76,  1,
       68, 71, 76, 75,  1, 71, 62,  1, 60, 65, 62, 62, 61, 74, 61])>)
(<tf.Tensor: shap

In [37]:
#lets have a look at a sample of our input and output data
for input_example, target_example in  dataset.take(1):
  print ('Input data ',repr(''.join(char_arr[input_example.numpy()])))
  print ('Output data ',repr(''.join(char_arr[target_example.numpy()])))

Input data  'Human 1: Hi!\nHuman 2: What is your favorite holiday?\nHuman 1: one where I get to meet lots of differ'
Output data  'uman 1: Hi!\nHuman 2: What is your favorite holiday?\nHuman 1: one where I get to meet lots of differe'


The above example shows the importance of RNN layer. 
We provide n input and the output takes from 2 index to n+1 index

In [38]:
BATCH_SIZE = 64

# Buffer size to shuffle the dataset
# (TF data is designed to work with possibly infinite sequences,
# so it doesn't attempt to shuffle the entire sequence in memory. Instead,
# it maintains a buffer in which it shuffles elements).
BUFFER_SIZE = 10000

dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)

dataset

<BatchDataset shapes: ((64, 100), (64, 100)), types: (tf.int64, tf.int64)>

In [0]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension
embedding_dim = 256

# Number of RNN units
rnn_units = 1024

In [0]:
#model specification 

def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
  model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim,
                              batch_input_shape=[batch_size, None]),
    tf.keras.layers.GRU(rnn_units,
                        return_sequences=True,
                        stateful=True,
                        recurrent_initializer='glorot_uniform'),
    tf.keras.layers.Dense(vocab_size)
  ])
  return model

In [0]:
#model build up 

model = build_model(
  vocab_size = len(vocab),
  embedding_dim=embedding_dim,
  rnn_units=rnn_units,
  batch_size=BATCH_SIZE)

In [43]:
for input_example_batch, target_example_batch in dataset.take(1):
  example_batch_predictions = model(input_example_batch)
  print(example_batch_predictions.shape, "# (batch_size, sequence_length, vocab_size)")

(64, 100, 101) # (batch_size, sequence_length, vocab_size)


In [44]:
def loss(labels, logits):
  return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)

example_batch_loss  = loss(target_example_batch, example_batch_predictions)
print("Prediction shape: ", example_batch_predictions.shape, " # (batch_size, sequence_length, vocab_size)")
print("scalar_loss:      ", example_batch_loss.numpy().mean())

Prediction shape:  (64, 100, 101)  # (batch_size, sequence_length, vocab_size)
scalar_loss:       4.6143174


In [0]:
#Compilation of model 
model.compile(optimizer='adam', loss=loss)

In [0]:
checkpoint_dir="chkpts"
check_point_pref=os.path.join(checkpoint_dir,'chkpts_{epoch}')

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(filepath=check_point_pref,save_weights_only=True)

In [0]:
#now training our model

EPOCHS=40
history = model.fit(dataset, epochs=EPOCHS,callbacks=[checkpoint_callback])

In [49]:
#latest checkpoint
tf.train.latest_checkpoint(checkpoint_dir)

'chkpts/chkpts_40'

In [0]:
#building model from last checkpoint 
model = build_model(vocab_size, embedding_dim, rnn_units, batch_size=1)

model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))

model.build(tf.TensorShape([1, None]))

In [51]:
#summary of model
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (1, None, 256)            25856     
_________________________________________________________________
gru_1 (GRU)                  (1, None, 1024)           3938304   
_________________________________________________________________
dense_1 (Dense)              (1, None, 101)            103525    
Total params: 4,067,685
Trainable params: 4,067,685
Non-trainable params: 0
_________________________________________________________________


In [0]:
#text generation function 

def generate_text(model, start_string):
  # Evaluation step (generating text using the learned model)

  # Number of characters to generate
  num_generate = 300

  # Converting our start string to numbers (vectorizing)
  input_eval = [mapping[s] for s in start_string]
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty string to store our results
  text_generated = []

  # Low temperatures results in more predictable text.
  # Higher temperatures results in more surprising text.
  # Experiment to find the best setting.
  temperature = 1.0

  # Here batch size == 1
  model.reset_states()
  for i in range(num_generate):
      predictions = model(input_eval)
      # remove the batch dimension
      predictions = tf.squeeze(predictions, 0)

      # using a categorical distribution to predict the word returned by the model
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # We pass the predicted word as the next input to the model
      # along with the previous hidden state
      input_eval = tf.expand_dims([predicted_id], 0)

      text_generated.append(char_arr[predicted_id])

  return (start_string + ''.join(text_generated))

In [70]:
#testing phase 

while(True):
  print('enter text or type quit to exit')
  feed=input()
  if feed=='quit':
    break
  else:
    get_string=u"Human 1: "+feed+"\nHuman 2: "
  output=generate_text(model, start_string=get_string).splitlines()
  for each in output[:2]:
    print(each)

enter text or type quit to exit
hi buddy
Human 1: hi buddy
Human 2: you at for that?
enter text or type quit to exit
my pleasure
Human 1: my pleasure
Human 2: hahaha
enter text or type quit to exit
weather
Human 1: weather
Human 2: What's your favorite shorts?
enter text or type quit to exit
tee
Human 1: tee
Human 2: I haven't thought it was a bunch of fun. what do you loved proformer. Why do Heave it had a pain. It's Vaisto doing some balance between the toptions govivally, my daychis world ... so on. like that's kind of an excere that I know too macho lates and we didn't have a feel theor insountalite it undes
enter text or type quit to exit
how are you?
Human 1: how are you?
Human 2: I'm doing great haha. Also mimate should be vacation ser someone who is nuch up on 1. Did never seew hiking watched
enter text or type quit to exit
your name?
Human 1: your name?
Human 2: I don't know them. It's just see easy to e. Hope you also stirno to meeth and street food. Cakewing But York has by 