<a href="https://colab.research.google.com/github/projjal1/Neural_Networks_Projects/blob/master/Predict_Iris_Name.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing all the required libraries for the ML task

In [ ]:
import pandas as pd
import numpy as np

Read the .data file from the ICS archive 

In [ ]:
data=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',names=['sepal length', 'sepal width', \
                                                       'petal length', "petal width",
                                                      'Species'])

Lets look at few rows of dataset 

In [ ]:
data.head()

sepal length  sepal width  petal length  petal width      Species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Shape of the dataset in rows and columns

In [ ]:
print("Dataset has {0} rows and {1} columns.".format(data.shape[0],data.shape[1]))

Dataset has 150 rows and 5 columns.


Extracting labels from the dataset

In [ ]:
labels=data.Species.values
labels[:5]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

Dropping label('Species') column and then extracting features from data

In [ ]:
data=data.drop(['Species'],axis=1)
params=data.values
params[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

Encoding labels using Label Encoder from sklearn library

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencode=LabelEncoder()
labels=labelencode.fit_transform(labels)

In [ ]:
set(labels)

{0, 1, 2}

Splitting the dataset into train and test set

In [ ]:
from sklearn.model_selection import train_test_split

test_size=0.25

#Divide the dataset into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(params,labels, test_size=test_size, random_state = 0) 

Applying normalization on the parameters in the dataset

In [ ]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [ ]:
print(X_train[:3])
print(X_test[:3])

[[ 0.01543995 -0.11925475  0.22512685  0.35638175]
 [-0.09984503 -1.04039491  0.11355956 -0.02864805]
 [ 1.05300481 -0.11925475  0.95031423  1.12644135]]
[[ 0.12564197 -0.6117992   0.88098019  1.81979323]
 [ 0.42404164 -2.0207913   0.21386113 -0.1846167 ]
 [-0.32195754  2.67584903 -1.36296573 -1.32999381]]


Applying Naive-Bayes classfication model on the ML task

In [ ]:
# import Naive-Bayes library
from sklearn.naive_bayes import GaussianNB

model=GaussianNB()

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

Prediction and metrics analysis

In [ ]:
#Calculating the Accuracy of the predictions
from sklearn import metrics
print("Prediction Accuracy = ", metrics.accuracy_score(y_test, y_pred))

Prediction Accuracy =  0.868421052631579
